#+title: Curriculum Vitae
#+author: Adrian Adermon
#+type: CV

|                   |                                                 |
|-------------------+-------------------------------------------------|
| Postal address:   | IFAU, P.O. Box 513, 752 20 Uppsala, Sweden      |
| Visiting address: | IFAU, Kyrkogårdsgatan 6, 753 12 Uppsala, Sweden |
| Telephone:        | [[tel:+46184717086][+46 (0)18 471 70 86]]                             |
| Email:            | [[mailto:adrian.adermon@ifau.uu.se][adrian.adermon@ifau.uu.se]]                       |
| Website:          | [[https://www.adrianadermon.com][www.adrianadermon.com]]                           |

* Current position

Researcher, Institute for Evaluation of Labour Market and Education Policy (IFAU), Uppsala, 2016--.

* Affiliations

Uppsala Center for Labor Studies (UCLS), Uppsala Center for Fiscal Studies (UCFS), and Uppsala Immigration Lab (UIL), Uppsala University.

Research Fellow, IZA, 2024--

Research Fellow, Rockwool Foundation Berlin, 2025--

* Previous experience

Assistant professor, Department of Economics and Uppsala Center for Labor Studies, Uppsala University, 2013--2016.

Visiting scholar, Center for Equitable Growth, UC Berkeley, September 2015--March 2016.

* Education and degrees

- Associate professor (docent) in Economics, Uppsala University, 2023.
  
- Ph.D. in Economics, Uppsala University, 2013.

- Visiting student research collaborator, Princeton University, spring 2011.

- Master of Social Science in Economics, Uppsala University, 2007.

- Bachelor of Social Science in Statistics, Uppsala University, 2010.

* Ph.D. thesis

"Essays on the Transmission of Human Capital and the Impact of Technological Change", Economic Studies 135, Department of Economics, Uppsala University.

Defended June 7, 2013. Supervisor: Professor Mikael Lindahl. Assistant supervisor: Associate Professor Magnus Gustavsson. Discussant: Professor Markus Jäntti, Swedish Institute for Social Research.

* Fields of interest

Labor economics, intergenerational mobility, inequality, technological change.

* Current research projects
"Intergenerational mobility of immigrants in 15 destination countries", with 
Leah Boustan,
Mathias Fjællegaard Jensen,
Ran Abramitzky,
Elisa Jácome,
Alan Manning,
Santiago Pérez,
Analysia Watley,
Jaime Arellano-Bover,
Olof Åslund,
Marie Connolly,
Nathan Deutscher,
Anne C. Gielen,
Yvonne Giesing ,
Yajna Govind,
Martin Halla,
Dominik Hangartner,
Yuyan Jiang,
Cecilia Karmel,
Fanny Landaud,
Lindsey Macmillan,
Isabel Z. Martínez,
Alberto Polo,
Panu Poutvaara,
Hillel Rapoport,
Sara Roman,
Kjell G. Salvanes,
Shmuel San,
Michael Siegenthaler,
Louis Sirugue,
Javier Soria Espín,
Jan Stuhler,
Giovanni L. Violante,
Dinand Webbink,
Andrea Weber,
Jonathan Zhang,
Angela Zheng,
and
Tom Zohar.
Revise and resubmit at the /American Economic Review/.

"Understanding occupational wage growth", with Simon Ek, Georg Graetz, and Yaroslav Yakymovych.

"The Relationship Between Intergenerational Mobility and Equality of Opportunity", with Gunnar Brandén and Martin Nybom. Submitted.

# "The role of the immediate and extended family in the formation of wealth: Evidence from Sweden", with Kristin Gunnarsson.

# "Educational Mobility Across Three Generations: Measurement Error or Social Interactions?"

# "Sibling Spillovers in Education: Causal Estimates From a Natural Experiment"

* Journal articles (peer reviewed)

"Earnings Losses and the Role of the Welfare State During the COVID-19 Pandemic: Evidence from Sweden" (2024), with Lisa Laun, Patrik Lind, Martin Olsson, Jan Sauermann, and Anna Sjögren. /Review of Income and Wealth/ 70(4), 981--1010.

"Measuring Absolute Income Mobility: Lessons from North America and Europe" (2024), with Robert Manduca, Maximilian Hell, Jo Blanden, Espen Bratberg, Anne C. Gielen, Hans van Kippersluis, Keunbok Lee, Stephen Machin, Martin D. Munk, Martin Nybom, Yuri Ostrovsky, Sumaiya Rahman, and Outi Sirniö. /American Economic Journal: Applied Economics/ 16(2), 1--30.

"Gig-jobs: Stepping stones or dead ends?" (2022), with Lena Hensvik. /Labour Economics/ 76, 102171.

"Dynastic Human Capital, Inequality, and Intergenerational Mobility" (2021), with Mikael Lindahl and Mårten Palme. /American Economic Review/ 111(5), 1523--1548.

"Intergenerational Wealth Mobility and the Role of Inheritance: Evidence from Multiple Generations" (2018), with Mikael Lindahl and Daniel Waldenström. /The Economic Journal/ 128(612), F482--F513.

"Job Polarization and Task-Biased Technological Change: Evidence from Sweden, 1975--2005" (2015), with Magnus Gustavsson. /The Scandinavian Journal of Economics/ 117(3), 878--917.

"Piracy and music sales: The effects of an anti-piracy law" (2014), with Che-Yuan Liang. /Journal of Economic Behavior & Organization/ 105, 90--106.

* Book chapters

"Innovation Matters: An Empirical Analysis of Innovation 2002--2004 and Its Impact on Productivity", with Hans-Olof Hagén, Caroline Ahlstrand, Martin Daniels, and Emma Nilsson. In /Yearbook on Productivity 2007/. Saltsjöbaden: Statistics Sweden, 2008, 33--62.

* Other publications

"Coronapandemin, arbetsinkomsterna och välfärdsystemets skyddsgrad: Befolkningens inkomstutveckling under 2020", with Lisa Laun, Patrik Lind, Martin Olsson, Jan Sauermann, and Anna Sjögren. Background report for the Swedish Corona Commission. Also published as IFAU Rapport 2022:3. 

"Social rörlighet", with Mikael Lindahl and Mårten Palme. /SNS Analys/ 82 (2021).

"Gigekonomin som dörröppnare?", with Lena Hensvik. IFAU Rapport 2020:22.

"Trender i absolut inkomströrlighet i Europa och Nordamerika", with Robert Manduca, Maximilian Hell, Adrian Adermon, Jo Blanden, Espen Bratberg, Anne C. Gielen, Hans van Kippersluis, Keun Bok Lee, Stephen Machin, Martin D. Munk, Martin Nybom, Yuri Ostrovsky, Sumaiya Rahman, and Outi Sirniö. IFAU Rapport 2020:13.

"Bristyrken i offentlig verksamhet --- Var arbetar de utbildade?", with Lisa Laun. /Ekonomisk Debatt/ 7/2019.

"Bristyrken i offentlig verksamhet --- Var arbetar de utbildade?", with Lisa Laun. IFAU Rapport 2018:19.

"Förmögenhet och arv över flera generationer", with Mikael Lindahl and Daniel Waldenström. IFAU Rapport 2018:7.

"Den utvidgade familjens betydelse för barns utbildning", with Mikael Lindahl and Mårten Palme. IFAU Rapport 2016:16.

"Teknisk utveckling och jobbpolarisering", with Magnus Gustavsson. /SNS Analys/ 28 (2015).

"Fildelning och musikförsäljning --- Effekten av piratjägarlagen IPRED", with Che-Yuan Liang. /Ekonomisk Debatt/ 3/2015.

* Invited seminar presentations
- The Migration Studies Delegation (Delmi), Stockholm, May 2025.

- Department of Economics and Statistics, Linnaeus University, Växjö, February 2025.
  
- VATT Institute for Economic Research, Helsinki, April 2023.

- Ratio Institute, Stockholm, February 2023.

- Division of Developmental Psychology, Department of Psychology, Uppsala University, November 2022.

- Research group Epidemiology of Chronic Diseases, The Arctic University of Norway, Tromsø, October 2021.

- Swedish Ministry of Finance, Stockholm, April 2019.

- Research Institute of Industrial Economics, Stockholm, April 2019.

- Swedish Ministry of Education and Research, Stockholm, November 2018.

- School of Business and Economics, Linnaeus University, Växjö, October 2017.

- Research Institute of Industrial Economics, Stockholm, September 2017.

- Department of Economics, Umeå University, May 2017.

- Swedish Ministry of Finance, Stockholm, February 2017.

- Swedish Ministry of Education and Research, Stockholm, November 2016.

- Department of Economics, University of California, Berkeley, February 2016.

- Swedish Institute for Social Research (SOFI), Stockholm, November 2012.

- The Danish National Centre for Social Research (SFI), Copenhagen, October 2012.

* Conference and workshop presentations
- Workshop on Immigrant Assimilation, Princeton, May 2025.

- Workshop on Wealth Inequality, Intergenerational Mobility, and Equality of Opportunity, Vienna, November 2024.
  
- Uppsala Immigration Lab workshop, Uppsala, October 2024.

- UIL/Urban Lab workshop, Rånäs, January 2023.

- Workshop in Labour Economics: Wages, Employment and Inequality, Helsinki, August 2023.

- Swedish conference in Economics, Stockholm, November 2022.

- Frontiers in Econometrics Workshop, Bern, May 2022.

- Genes, Social Mobility, and Inequalities across the Life-Course, virtual, July 2021.

- EALE/SOLE/AASLE World Conference, virtual, June 2020.

- The impact of childhood circumstances on individual outcomes over the life-course (IMCHILD) Workshop, Stockholm, September 2019.

- Meeting of the Society for the Study of Economic Inequality (ECINEQ), Paris, July 2019.

- Nordic Summer Institute in Labor Economics, Uppsala, June 2019.

- Dynamics of Inequality Across the Lifecourse (DIAL), Mid-term Conference, Turku, June 2019.

- Paris-Uppsala Workshop on Income and Wealth, Paris, November 2018.

- Workshop on New Developments in Intergenerational Mobility, Rotterdam, September 2018.

- Annual Congress of the European Economic Association (EEA), Cologne, August 2018.

- Meeting of the Society for the Study of Economic Inequality (ECINEQ), New York, July 2017.

- Allied Social Sciences Associations Annual Meeting (ASSA), Chicago, January 2017.

- National Conference of Swedish Economists in Gothenburg, September 2016.

- Annual Congress of the European Economic Association (EEA), Geneva, August 2016.

- Workshop on the Intergenerational Transmission of Economic Status, Madrid, May 2016.

- Uppsala Center For Labor Studies Members Meeting, Krusenberg, August 2015.

- Conference on Taxation, Household Behavior, and the Distribution of Incomes and Wealth, Berlin, July 2015.

- Meeting of the Society for the Study of Economic Inequality (ECINEQ), Luxembourg, July 2015.

- Annual Conference of the European Society for Population Economics (ESPE), Braga, June 2014.

- Workshop on Family and Gender, Honningsvåg, August 2013.

- National Conference of Swedish Economists in Stockholm, September 2012.

- Annual Conference of the European Association of Labour Economists (EALE), Bonn, September 2012.

- Annual Congress of the European Economic Association (EEA), Malaga, August 2012.

- Annual Conference of the European Society for Population Economics (ESPE), Bern, June 2012.

- Stockholm-Uppsala Doctoral Student Workshop in Economics in Uppsala, May 2012.

- National Conference of Swedish Economists in Uppsala, September 2011.

- Uppsala Center For Labor Studies Members Meeting, Uppsala, October 2010.

- Stockholm-Uppsala Doctoral Student Workshop in Economics in Stockholm, May 2010.

- Stockholm-Uppsala Doctoral Student Workshop in Economics in Uppsala, May 2009.

* Other presentations and seminars

- IFAU labor market day, Panel discussion on the future of labor market policy, Stockholm, September 2024.
  
- Swedish JobTech, Panel discussion on the gig economy, Stockholm, April 2024.

- European Commission, Panel discussion on A.I. and the labor market, Stockholm, October 2019.

- Swedish National Agency for Education, Workshop for teachers, Stockholm, September 2019.

- Forte and Uppsala Center for Labor Studies Conference, Uppsala, May 2019.

- Fores, Stockholm, March 2018.

- Wallenberg Foundation, Stockholm, November 2017.

- Almedalen, Visby, July 2016.

- Fores, Stockholm, April 2016.

- SNS, Stockholm, March 2015.

* Referee assignments

American Economic Journal: Applied Economics,
CESifo Economic Studies,
Economic Inquiry,
The Economic Journal,
European Economic Review,
European Journal of Law and Economics,
European Sociological Review,
FinanzArchiv/European Journal of Public Finance,
Gender & Society,
Industrial Relations,
Information Economics and Policy,
Journal of Cultural Economics,
The Journal of Economic Inequality,
Journal of the European Economic Association,
Journal of Evolutionary Economics,
Journal of Human Resources,
The Journal of Industrial Economics,
Journal of Population Economics,
Journal of Public Economics,
Labour Economics,
Oxford Bulletin of Economics and Statistics,
Oxford Economic Papers,
The Review of Economics and Statistics,
The Review of Economic Studies,
The Review of Income and Wealth,
The Scandinavian Journal of Economics,
Social Forces,
Social Science History,
Social Science Research,
World Development.

* Grant review assignments

European Research Council.

* Scholarships and grants

Swedish Research Council for Health, Working Life and Welfare (Forte), "Labor market integration of immigrants over multiple generations", project grant, 2025--2027, SEK 5 million, principal investigator, with Mattias Engdahl, Anders Forslund, Erica Lindahl, Martin Nybom, Mårten Palme, Sara Roman, and Olof Åslund.

Swedish Research Council (VR), "Incomes, inequality and the welfare system during the corona pandemic", project grant, 2023--2025, SEK 3.6 million, co-applicant, with Jan Sauermann (PI), Lisa Laun, Martin Olsson, and Anna Sjögren.

NORFACE Dial, "The impact of childhood circumstances on individual outcomes over the life-course", multi-national research project 2018--2020, co-applicant, with Andreas Peichl, Alain Trannoy, Daniel Waldenström, and Arnaud Lefranc (PIs), et. al.

Travel grant for visiting University of California, Berkeley, Jan Wallander and Tom Hedelius Foundation, SEK 200,000, 2015.

Wallander Scholarship, 3 year independent research grant awarded to young economists, Jan Wallander and Tom Hedelius Foundation, SEK 1.5 million, 2013.

Hedelius Scholarship for financing one semester of graduate studies at a Princeton University, Jan Wallander and Tom Hedelius Foundation, SEK 300,000, 2009.

* Administrative experience

Seminar series organizer, IFAU, 2019--2022.

Member of the organizing committee for Stockholm-Uppsala Doctoral Student Workshop in Economics (SUDSWEc), May 10, 2012 in Uppsala.

Member of the organizing committee for Stockholm-Uppsala Doctoral Student Workshop in Economics (SUDSWEc), May 15, 2009 in Uppsala.

* Teaching and supervision experience

- Assistant supervisor of PhD-candidate Tsz Chun Kwok, 2024--.

- Assistant supervisor of PhD-candidate Yaroslav Yakymovych, 2018--2022.

- Assistant supervisor of PhD-candidate Kristin Gunnarsson, 2016--2017.

- Lecturer, Machine Learning with Economic and Financial Applications (Uppsala University, master level), 2025--.

- Lecturer, Topics in Econometrics (Uppsala University, master level), 2014--2024.

- Lecturer, Labor II: Advanced Topics in Labor Economics (Uppsala University, Ph.D. level), 2017.

- Lecturer, Applied Microeconometrics (Uppsala University, Ph.D. level), 2013--2014.

- Teaching assistant and guest lecturer, Microeconomics (Uppsala University, undergraduate level), 2019--2020.

- Teaching assistant, Basic Micro- and Macro Theory (Uppsala University, undergraduate level), 2008--2009.

- Supervisor of Master's Theses (Uppsala University), 2018, 2025.

- Supervisor of Bachelor's Theses (Uppsala University), 2014--2015.

* Discussant and committee assignments
Member of Ph.D. grading committee for Valentin Zulj, Uppsala University, October 2025.

Discussant at final seminar for Malin Backman's Ph.D. thesis manuscript, Uppsala University, February 2024.

Member of Ph.D. grading committee for Erik Liss, Linköping University, January 2024.

Discussant at licentiate seminar for Malin Backman, Uppsala University, June 2023.

Discussant at final seminar for André Richter's Ph.D. thesis manuscript, SOFI, Stockholm University, October 2016.

Discussant at final seminar for Mengyi Cao's Ph.D. thesis manuscript, Stockholm University, September 2016.

* Awards and honors

Excellence in Reviewing Award (top 25 reviewer), /Labour Economics/, 2017.

* Personal

Born in 1981. Swedish citizenship.
