name: Convert CV to PDF

on:
  push:
    paths:
      - 'content/CV/index.org'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.14
        with:
          args: >-  # allows you to break string into multiple lines
            --standalone
            --output=static/pdf/CV.pdf
            --pdf-engine=xelatex
            --include-in-header=static/tex/latex_header.tex
            --variable=subparagraph
            --variable papersize=a4
            --lua-filter=static/lua/current_date.lua
            content/CV/index.org
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
